name: Building and Deploying on Pi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DISCORD_BOT_TOKEN: ${{ vars.DISCORD_BOT_TOKEN }}
  DISCORD_APP_ID: ${{ vars.DISCORD_APP_ID }}
  TEST_GUILD_ID: ${{ vars.TEST_GUILD_ID }}
  YOUTUBE_TOKEN: ${{ vars.YOUTUBE_TOKEN }}

jobs:

  pull:

    runs-on: homegrown

    steps:
    - uses: actions/checkout@v3
    - name: Pull latest changes to raspberry
      run: git pull origin master

  image:

    runs-on: homegrown

    needs: pull

    steps:
    - uses: actions/checkout@v3
    - name: Create a container and start it
      run: docker build -t boomtsy .

  run:

    runs-on: homegrown

    needs: [pull, image]

    environment: production

    steps:
    - uses: actions/checkout@v3
    - name: Create a container and start it
      run: docker run -dp 80:${{ vars.WEBSERVER_PORT }} boomtsy
