name: Building and Deploying on Pi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  pull:

    runs-on: homegrown

    steps:
    - uses: actions/checkout@v3
    - name: Pull latest changes to raspberry
      run: git pull origin master
