name: Building and Deploying on Pi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  env:
    runs-on: homegrown
    environment: production
    steps:
    - name: Create env file for container
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
        TEST_GUILD_ID: ${{ secrets.TEST_GUILD_ID }}
        YOUTUBE_TOKEN: ${{ secrets.YOUTUBE_TOKEN }}
        WEBSERVER_PORT: ${{ vars.WEBSERVER_PORT }}
      run: |
        touch .env
        echo DISCORD_BOT_TOKEN="$DISCORD_BOT_TOKEN" >> .env
        echo DISCORD_APP_ID="$DISCORD_APP_ID" >> .env
        echo TEST_GUILD_ID="$TEST_GUILD_ID" >> .env
        echo YOUTUBE_TOKEN="$YOUTUBE_TOKEN" >> .env
        echo WEBSERVER_PORT="$WEBSERVER_PORT" >> .env
        cat .env

  pull:
    runs-on: homegrown
    steps:
    - uses: actions/checkout@v3
    - name: Pull latest changes to raspberry
      run: git pull origin master

  image:
    runs-on: homegrown
    needs: pull
    steps:
    - name: Create a container and start it
      run: docker build -t boomtsy .

  run:
    runs-on: homegrown
    needs: [pull, image, env]
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Create a container and start it
      run: docker run -dp 80:${{ vars.WEBSERVER_PORT }} boomtsy
