name: Building and Deploying on Pi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  pull:

    runs-on: homegrown

    steps:
    - uses: actions/checkout@v3
    - name: Pull latest changes to raspberry
      run: git pull origin master

  image:

    runs-on: homegrown

    needs: pull

    steps:
    - uses: actions/checkout@v3
    - name: Create a container and start it
      run: docker build -t boomtsy .

  run:

    runs-on: homegrown

    needs: [pull, image]

    steps:
    - uses: actions/checkout@v3
    - name: Create a container and start it
      run: docker run -dp 80:${{ vars.WEBSERVER_PORT }} boomtsy
